### ISSUE TITLE
Build error Kernel 6.1.14

### ISSUE THREAD

**Issue by SirLouen** [c---/applesmc-next#2]
Fedora 37
Kernel: 6.1.14-200.fc37.x86_64

```
# cat /var/lib/dkms/applesmc-next/0.1.4/build/make.log 
DKMS make.log for applesmc-next-0.1.4 for kernel 6.1.14-200.fc37.x86_64 (x86_64)
Thu Mar  9 02:20:14 PM CET 2023
make -C /lib/modules/6.1.14-200.fc37.x86_64/build M=`pwd`
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/usr/src/kernels/6.1.14-200.fc37.x86_64'
  CC [M]  /var/lib/dkms/applesmc-next/0.1.4/build/applesmc/applesmc.o
/var/lib/dkms/applesmc-next/0.1.4/build/applesmc/applesmc.c:1324:24: error: initialization of ‘int (*)(struct power_supply *)’ from incompatible pointer type ‘int (*)(struct power_supply *, struct acpi_battery_hook *)’ [-Werror=incompatible-pointer-types]
 1324 |         .add_battery = applesmc_battery_add,
      |                        ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/applesmc-next/0.1.4/build/applesmc/applesmc.c:1324:24: note: (near initialization for ‘battery_hook.add_battery’)
/var/lib/dkms/applesmc-next/0.1.4/build/applesmc/applesmc.c:1325:27: error: initialization of ‘int (*)(struct power_supply *)’ from incompatible pointer type ‘int (*)(struct power_supply *, struct acpi_battery_hook *)’ [-Werror=incompatible-pointer-types]
 1325 |         .remove_battery = applesmc_battery_remove,
      |                           ^~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/applesmc-next/0.1.4/build/applesmc/applesmc.c:1325:27: note: (near initialization for ‘battery_hook.remove_battery’)
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:250: /var/lib/dkms/applesmc-next/0.1.4/build/applesmc/applesmc.o] Error 1
make[2]: *** [scripts/Makefile.build:500: /var/lib/dkms/applesmc-next/0.1.4/build/applesmc] Error 2
make[1]: *** [Makefile:2009: /var/lib/dkms/applesmc-next/0.1.4/build] Error 2
make[1]: Leaving directory '/usr/src/kernels/6.1.14-200.fc37.x86_64'
```

**Comment by c---** [comment]
For a quick fix try checking out tag 0.1.3 3f500c4044a0a3eacd75f72ebb2e307f0ef21cee

There is no functional difference, just kernel changes. Honestly I didn't even know people were using this module. I will add changes so that it can compile on the various kernels automatically.

**Comment by SirLouen** [comment]
> For a quick fix try checking out tag 0.1.3 [3f500c4](https://github.com/c---/applesmc-next/commit/3f500c4044a0a3eacd75f72ebb2e307f0ef21cee)
> 
> There is no functional difference, just kernel changes. Honestly I didn't even know people were using this module. I will add changes so that it can compile on the various kernels automatically.

I'm not where is the issue you are poiting out.

I've tried reverting to this code but it doesn't seem to work with 0.1.4

```
wget --no-if-modified-since -N https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/plain/drivers/acpi/sbs.c
wget --no-if-modified-since -N https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/plain/drivers/acpi/sbshc.h
wget --no-if-modified-since -N https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/plain/drivers/hwmon/applesmc.c
```

I've simply reverted full to 0.1.3 and it works fine.

I think the problems come from that `acpi_battery_hook` you introduced in the latest patch.

[Someone reported something similar 3 days ago here](https://bugs.launchpad.net/ubuntu/+source/librem-ec-acpi/+bug/2009511)

**Comment by c---** [comment]
@SirLouen Yes, I meant revert to 0.1.3 and that there is no functional difference between 0.1.3 and 0.1.4. The only difference is the kernel API used.

The problem is that the kernel API keeps changing so I'm adding checks that changes the code depending on the kernel version.

**Comment by SirLouen** [comment]
> @SirLouen Yes, I meant revert to 0.1.3 and that there is no functional difference between 0.1.3 and 0.1.4. The only difference is the kernel API used.
> 
> The problem is that the kernel API keeps changing so I'm adding checks that changes the code depending on the kernel version.

If you need some debugging info, tell me how to set it.

Moreover, in my laptop (Fedora 37 + Macbook Air Mid 2012 A1466), the full threshold doesn't change the LED in the charger when the threshold is reached. Do you think this could be a misbehavior worth a new issue, or this is simply not currently working?

**Comment by c---** [comment]
@SirLouen Yes, please create another issue for the charge LED not working. Apple may have changed something between models. Thanks!

**Comment by c---** [comment]
Hopefully this is fixed by f6de0f159ee034c8b8444dbb0f5d00b0be6a6c97 version 0.1.5

I only tested with the Arch Linux 6.1.19 kernel though.

**Comment by SirLouen** [comment]
> Hopefully this is fixed by [f6de0f1](https://github.com/c---/applesmc-next/commit/f6de0f159ee034c8b8444dbb0f5d00b0be6a6c97) version 0.1.5
> 
> I only tested with the Arch Linux 6.1.19 kernel though.

I'm going to update Fedora's kernel this week and I will post back with the results with 0.1.5

**Comment by SirLouen** [comment]
I cannot test this yet, because it says that current modules are not newer than the ones installed in the current kernel. As soon as there is a new kernel update that forces me a reinstall I will report

**Comment by SirLouen** [comment]
I got a kernel update to 6.2.8 and it's working on v1.0.5. Time to close this issue
