### ISSUE TITLE
Charging LED issue with full threshold

### ISSUE THREAD

**Issue by SirLouen** [c---/applesmc-next#3]
As mentioned here
https://github.com/c---/applesmc-next/issues/2#issuecomment-1464463274

Full Threshold is not working in my Macbook Air 2012 A1466 with Fedora 37 (although I also tested with latest Ubuntu and it did not work either).

It would be useful if you could provide me some debugging guide so I can give you more info of what is being sent by the laptop.

**Comment by c---** [comment]
The LED threshold is controlled by the "BFCL" SMC variable. I wonder if it only exists on newer firmware?

Somewhere I have a utility to dump all the SMC parameters but I need to find it. Or I believe MacOS has a utility too.

**Comment by SirLouen** [comment]
> Somewhere I have a utility to dump all the SMC parameters but I need to find it. Or I believe MacOS has a utility too.

I have completely wiped MacOS by now (low on HDD).  When you find it, post it so I can dump all SMC and post them here

**Comment by c---** [comment]
This is the script I use to dump the SMC from Linux:
```BASH
#!/bin/bash
CNT=$(cat /sys/devices/platform/applesmc.768/key_count)
((CNT--))
for i in $(seq 0 $CNT); do
   echo $i > /sys/devices/platform/applesmc.768/key_at_index
   NAME="$(cat /sys/devices/platform/applesmc.768/key_at_index_name)"
   TYPE="$(cat /sys/devices/platform/applesmc.768/key_at_index_type)"
   LEN="$(cat /sys/devices/platform/applesmc.768/key_at_index_data_length)"
   echo -n "$i name='$NAME' type='$TYPE' len='$LEN' value='"
   echo -n "$(cat /sys/devices/platform/applesmc.768/key_at_index_data|xxd -g0 -p -c128)"
   echo "'"
done
```
Maybe look for variables that start with "B".  There is some indication that the BFCL variable isn't supported on older Macs but if it exists on yours then maybe it's not being set correctly.

**Comment by SirLouen** [comment]
Not sure what I'm looking for with this command, still I've run it

``` 
79 name='BFCL' type='ui8 ' len='1' value=''
```

This is the only reference to BFCL

There is also a BATP

```
70 name='BATP' type='flag' len='1' value=''
```

**Comment by c---** [comment]
Are you getting an error about `xxd` not existing? The values all seem blank and that shouldn't be.

Try doing it manually:
```BASH
echo 79 > /sys/devices/platform/applesmc.768/key_at_index
cat /sys/devices/platform/applesmc.768/key_at_index_data|xxd -g0 -p -c128
```

**Comment by SirLouen** [comment]
Missing xxd package

```
79 name='BFCL' type='ui8 ' len='1' value='50'
```

**Comment by c---** [comment]
Well it's there and seems to be set correctly. You could try resetting the SMC then be careful that nothing writes to the BFCL then see if it exists after the reset. I'm trying to determine if it's showing up because it was written to or if it's there by default.

If it's there by default then I'm not quite sure what is going on. Does your charge light change color normally?

**Comment by SirLouen** [comment]
> You could try resetting the SMC then be careful that nothing writes to the BFCL then see if it exists after the reset.

How can I know which is the content of BFCL and that nothing is writting there?

> If it's there by default then I'm not quite sure what is going on. Does your charge light change color normally?

If I leave it go to 100% then it changes to green from orange. But if it's at 80% with full threshold, it stays in orange, regardless that it is "theorically fully charged". So basically the led only responds to 100% charge currently.

**Comment by c---** [comment]
Oh! Oops. I should have mentioned that even Apple sets the LED threshold a few percent less than 100%. I can't remember what the stock value is, something like 95%.

So if you have it charge to 80% you need to set the LED threshold to like 77% maybe 78%.  It's unlikely to ever hit exactly 80% on the charge level due to various factors.

**Comment by SirLouen** [comment]
> So if you have it charge to 80% you need to set the LED threshold to like 77% maybe 78%. It's unlikely to ever hit exactly 80% on the charge level due to various factors.

Tested 79% and it did not work, but with 78% it worked perfectly.

So, here is the issue solved. I would suggest putting this as a sidenote in the README.md
